# Generated by scripts/sync-backtest-contracts.py. Do not edit by hand.

BACKTEST_OHLCV_PROVIDER = "ccxt-public-readonly"
BACKTEST_OHLCV_DEFAULT_EXCHANGE = "binance"
BACKTEST_OHLCV_EXCHANGES = ("binance", "bybit", "okx", "kraken")
BACKTEST_EXECUTABLE_TIMEFRAMES = ("1m", "3m", "5m", "15m", "30m", "1h")
BACKTEST_MAX_COST_BPS = 1000
BACKTEST_RUN_EVENTS = {
    "queued": "backtest.queued",
    "dataStarted": "backtest.data.started",
    "dataPlanning": "backtest.data.planning",
    "dataCacheReusing": "backtest.data.cache_reusing",
    "dataFetching": "backtest.data.fetching",
    "dataExporting": "backtest.data.exporting",
    "dataCompleted": "backtest.data.completed",
    "executionStarted": "backtest.execution.started",
    "executionCompleted": "backtest.execution.completed",
    "indexingStarted": "backtest.indexing.started",
    "reportCompleted": "backtest.report.completed",
    "failed": "backtest.failed",
}
