import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by shadcn/AI Elements. These files remain covered by
    // TypeScript and Next build, but upstream registry internals currently
    // trigger React Compiler lint rules.
    "src/components/ai-elements/**",
    "src/components/ui/carousel.tsx",
  ]),
]);

export default eslintConfig;
