from __future__ import annotations

STATUS_STARTED = "started"
STATUS_PASS = "pass"
STATUS_FAIL = "fail"
STATUS_BLOCKED = "blocked"
STATUS_SKIPPED = "skipped"
EVENT_STATUSES = (STATUS_STARTED, STATUS_PASS, STATUS_FAIL, STATUS_BLOCKED, STATUS_SKIPPED)

FAILURE_MISSING_CREDENTIAL = "missing_credential"
FAILURE_PROVIDER_RATE_LIMITED = "provider_rate_limited"
FAILURE_PROVIDER_TIMEOUT = "provider_timeout"
FAILURE_PROVIDER_NOT_FOUND = "provider_not_found"
FAILURE_MALFORMED_RESPONSE = "malformed_response"
FAILURE_SCHEMA_INVALID = "schema_invalid"
FAILURE_POLICY_VIOLATION = "policy_violation"
FAILURE_STATIC_VALIDATION_FAILED = "static_validation_failed"
FAILURE_REVIEW_FAILED = "review_failed"
FAILURE_REVIEW_VALIDATION_DISAGREEMENT = "review_validation_disagreement"
FAILURE_ARTIFACT_MISSING = "artifact_missing"
FAILURE_FREE_CAPACITY_UNAVAILABLE = "free_capacity_unavailable"
FAILURE_TOOL_ERROR = "tool_error"
FAILURE_PROVIDER_ERROR = "provider_error"
FAILURE_UNKNOWN = "unknown"
FAILURE_CLASSES = (
    FAILURE_MISSING_CREDENTIAL,
    FAILURE_PROVIDER_RATE_LIMITED,
    FAILURE_PROVIDER_TIMEOUT,
    FAILURE_PROVIDER_NOT_FOUND,
    FAILURE_MALFORMED_RESPONSE,
    FAILURE_SCHEMA_INVALID,
    FAILURE_POLICY_VIOLATION,
    FAILURE_STATIC_VALIDATION_FAILED,
    FAILURE_REVIEW_FAILED,
    FAILURE_REVIEW_VALIDATION_DISAGREEMENT,
    FAILURE_ARTIFACT_MISSING,
    FAILURE_FREE_CAPACITY_UNAVAILABLE,
    FAILURE_TOOL_ERROR,
    FAILURE_PROVIDER_ERROR,
    FAILURE_UNKNOWN,
)
