#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from pprint import pformat
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from strategy_codebot.server.chat_intent_registry_validator import ChatIntentRegistryValidationError
from strategy_codebot.server.chat_intent_registry_validator import validate_chat_intent_registry_contract
from strategy_codebot.server.model_routing import DEFAULT_MODEL_STAGE
from strategy_codebot.server.model_routing import MODEL_STAGE_BALANCED_REVIEW
from strategy_codebot.server.model_routing import MODEL_STAGE_CLASSIFIER
from strategy_codebot.server.model_routing import MODEL_STAGE_PINE_CODE_GENERATION
from strategy_codebot.server.model_routing import MODEL_STAGE_REPAIR
from strategy_codebot.server.model_routing import MODEL_STAGE_STRATEGY_CODING

CONTRACT_PATH = ROOT / "contracts" / "chat-intent-registry.json"
WORKFLOW_CONTRACT_PATH = ROOT / "contracts" / "workflow-registry.json"


def load_contract(path: Path = CONTRACT_PATH) -> dict[str, Any]:
    contract = json.loads(path.read_text(encoding="utf-8"))
    validate_contract(contract, source=path)
    return contract


def validate_contract(contract: dict[str, Any], *, source: Path | str = CONTRACT_PATH) -> None:
    label = str(source)
    try:
        validate_chat_intent_registry_contract(
            contract,
            label=label,
            known_workflow_ids=_known_workflow_ids(),
            configured_model_stages=_configured_model_stages(),
        )
    except ChatIntentRegistryValidationError as exc:
        raise SystemExit(str(exc)) from exc


def _known_workflow_ids() -> set[str]:
    workflow_contract = json.loads(WORKFLOW_CONTRACT_PATH.read_text(encoding="utf-8"))
    workflows = workflow_contract.get("workflows")
    if not isinstance(workflows, dict) or not workflows:
        raise SystemExit(f"{WORKFLOW_CONTRACT_PATH} workflows must be a non-empty object")
    return {workflow_id for workflow_id in workflows if isinstance(workflow_id, str) and workflow_id}


def _configured_model_stages() -> set[str]:
    return {
        DEFAULT_MODEL_STAGE,
        MODEL_STAGE_BALANCED_REVIEW,
        MODEL_STAGE_CLASSIFIER,
        MODEL_STAGE_PINE_CODE_GENERATION,
        MODEL_STAGE_REPAIR,
        MODEL_STAGE_STRATEGY_CODING,
    }


def render_python(contract: dict[str, Any]) -> str:
    registry = pformat(contract, width=100, sort_dicts=False)
    return (
        "# Generated by scripts/sync-chat-intent-registry.py. Do not edit by hand.\n\n"
        "from __future__ import annotations\n\n"
        "from typing import Any\n\n"
        f"CHAT_INTENT_REGISTRY: dict[str, Any] = {registry}\n"
        f"CHAT_INTENT_SCHEMA_VERSION = {contract['schema_version']!r}\n"
        f"DOMAIN_SCOPES = {contract['domain_scopes']!r}\n"
        f"RESPONSE_INTENTS = {contract['response_intents']!r}\n"
        f"CHAT_INTENT_ACTIONS = {contract['actions']!r}\n"
        f"CHAT_INTENT_MODEL_STAGES = {contract['model_stages']!r}\n"
        f"WORKFLOW_INTENTS = {contract['workflow_intents']!r}\n"
        f"EVIDENCE_SIGNALS = {contract['evidence_signals']!r}\n"
    )


def render_typescript(contract: dict[str, Any]) -> str:
    intents = json.dumps(contract["response_intents"], indent=2)
    policies = json.dumps(
        _typescript_response_intent_policies(contract),
        indent=2,
    )
    return (
        "// Generated by scripts/sync-chat-intent-registry.py. Do not edit by hand.\n\n"
        f"export const CHAT_RESPONSE_INTENTS = {intents} as const;\n\n"
        "export type ChatResponseIntent = (typeof CHAT_RESPONSE_INTENTS)[number];\n\n"
        "const CHAT_RESPONSE_INTENT_SET = new Set<string>(CHAT_RESPONSE_INTENTS);\n\n"
        "export const CHAT_RESPONSE_INTENT_POLICIES = "
        f"{policies} satisfies Record<\n"
        "  ChatResponseIntent,\n"
        "  {\n"
        "    readonly currentContextAllowed: boolean;\n"
        "    readonly readonlyWebSearchAllowed: boolean;\n"
        "    readonly allowedWorkflowIntents: readonly string[];\n"
        "    readonly ui: {\n"
        "      readonly showStrategyProfile: boolean;\n"
        "      readonly marketToStrategySuggestion: boolean;\n"
        "    };\n"
        "  }\n"
        ">;\n\n"
        "export function isChatResponseIntent(value: unknown): value is ChatResponseIntent {\n"
        '  return typeof value === "string" && CHAT_RESPONSE_INTENT_SET.has(value);\n'
        "}\n\n"
        "export function shouldShowStrategyProfileForIntent(intent: ChatResponseIntent | null): boolean {\n"
        "  return Boolean(intent && CHAT_RESPONSE_INTENT_POLICIES[intent]?.ui.showStrategyProfile);\n"
        "}\n\n"
        "export function shouldSuggestMarketToStrategyForIntent(intent: ChatResponseIntent | null): boolean {\n"
        "  return Boolean(intent && CHAT_RESPONSE_INTENT_POLICIES[intent]?.ui.marketToStrategySuggestion);\n"
        "}\n"
    )


def _typescript_response_intent_policies(contract: dict[str, Any]) -> dict[str, Any]:
    ui_policies = contract["response_intent_ui_policies"]
    rendered: dict[str, Any] = {}
    for intent, policy in contract["response_intent_policies"].items():
        ui_policy = ui_policies[intent]
        rendered[intent] = {
            "allowedWorkflowIntents": policy["allowed_workflow_intents"],
            "currentContextAllowed": policy["current_context_allowed"],
            "readonlyWebSearchAllowed": policy["readonly_web_search_allowed"],
            "ui": {
                "marketToStrategySuggestion": ui_policy["market_to_strategy_suggestion"],
                "showStrategyProfile": ui_policy["show_strategy_profile"],
            },
        }
    return rendered


def generated_files(contract: dict[str, Any]) -> dict[Path, str]:
    return {
        ROOT / "src" / "strategy_codebot" / "server" / "chat_intent_registry_contract.py": render_python(contract),
        ROOT / "apps" / "web" / "src" / "lib" / "chat-intent-registry-contract.ts": render_typescript(contract),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    contract = load_contract()
    files = generated_files(contract)
    if args.write:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        return 0

    drifted = []
    for path, expected in files.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            actual = None
        if actual != expected:
            drifted.append(str(path.relative_to(ROOT)))
    if drifted:
        print("Chat intent registry generated files are stale:")
        for path in drifted:
            print(f"- {path}")
        print("Run: scripts/sync-chat-intent-registry.py --write")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
