#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "contracts" / "backtest-ohlcv.json"


def load_contract() -> dict[str, object]:
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    allowed = contract.get("allowed_exchanges")
    default = contract.get("default_exchange")
    provider = contract.get("provider")
    timeframes = contract.get("executable_timeframes")
    max_cost_bps = contract.get("max_cost_bps")
    run_events = contract.get("run_events")
    if not isinstance(provider, str) or not provider:
        raise SystemExit("contracts/backtest-ohlcv.json provider must be a non-empty string")
    if not isinstance(default, str) or not default:
        raise SystemExit("contracts/backtest-ohlcv.json default_exchange must be a non-empty string")
    if not isinstance(allowed, list) or not allowed or any(not isinstance(item, str) or not item for item in allowed):
        raise SystemExit("contracts/backtest-ohlcv.json allowed_exchanges must be a non-empty string array")
    if len(set(allowed)) != len(allowed):
        raise SystemExit("contracts/backtest-ohlcv.json allowed_exchanges must not contain duplicates")
    if default not in allowed:
        raise SystemExit("contracts/backtest-ohlcv.json default_exchange must be in allowed_exchanges")
    if not isinstance(timeframes, list) or not timeframes or any(not isinstance(item, str) or not item for item in timeframes):
        raise SystemExit("contracts/backtest-ohlcv.json executable_timeframes must be a non-empty string array")
    if len(set(timeframes)) != len(timeframes):
        raise SystemExit("contracts/backtest-ohlcv.json executable_timeframes must not contain duplicates")
    if not isinstance(max_cost_bps, int) or max_cost_bps < 0:
        raise SystemExit("contracts/backtest-ohlcv.json max_cost_bps must be a non-negative integer")
    if not isinstance(run_events, dict) or not run_events:
        raise SystemExit("contracts/backtest-ohlcv.json run_events must be a non-empty object")
    if any(not isinstance(key, str) or not key or not isinstance(value, str) or not value for key, value in run_events.items()):
        raise SystemExit("contracts/backtest-ohlcv.json run_events keys and values must be non-empty strings")
    if len(set(run_events.values())) != len(run_events):
        raise SystemExit("contracts/backtest-ohlcv.json run_events values must not contain duplicates")
    return contract


def python_tuple(values: list[object]) -> str:
    rendered = ", ".join(json.dumps(item) for item in values)
    if len(values) == 1:
        rendered = f"{rendered},"
    return f"({rendered})"


def python_dict(values: dict[str, object]) -> str:
    lines = ["{"]
    for key, value in values.items():
        lines.append(f"    {json.dumps(key)}: {json.dumps(value)},")
    lines.append("}")
    return "\n".join(lines)


def render_python(contract: dict[str, object]) -> str:
    provider = json.dumps(contract["provider"])
    default = json.dumps(contract["default_exchange"])
    exchanges = python_tuple(contract["allowed_exchanges"])  # type: ignore[arg-type]
    timeframes = python_tuple(contract["executable_timeframes"])  # type: ignore[arg-type]
    run_events = python_dict(contract["run_events"])  # type: ignore[arg-type]
    return (
        "# Generated by scripts/sync-backtest-contracts.py. Do not edit by hand.\n\n"
        f"BACKTEST_OHLCV_PROVIDER = {provider}\n"
        f"BACKTEST_OHLCV_DEFAULT_EXCHANGE = {default}\n"
        f"BACKTEST_OHLCV_EXCHANGES = {exchanges}\n"
        f"BACKTEST_EXECUTABLE_TIMEFRAMES = {timeframes}\n"
        f"BACKTEST_MAX_COST_BPS = {contract['max_cost_bps']}\n"
        f"BACKTEST_RUN_EVENTS = {run_events}\n"
    )


def render_typescript(contract: dict[str, object]) -> str:
    provider = json.dumps(contract["provider"])
    default = json.dumps(contract["default_exchange"])
    allowed = ", ".join(json.dumps(item) for item in contract["allowed_exchanges"])
    timeframes = ", ".join(json.dumps(item) for item in contract["executable_timeframes"])
    run_events = json.dumps(contract["run_events"], indent=2)
    return (
        "// Generated by scripts/sync-backtest-contracts.py. Do not edit by hand.\n\n"
        f"export const BACKTEST_OHLCV_PROVIDER = {provider} as const;\n"
        f"export const BACKTEST_OHLCV_DEFAULT_EXCHANGE = {default} as const;\n"
        f"export const BACKTEST_OHLCV_EXCHANGES = [{allowed}] as const;\n"
        f"export const BACKTEST_EXECUTABLE_TIMEFRAMES = [{timeframes}] as const;\n"
        f"export const BACKTEST_MAX_COST_BPS = {contract['max_cost_bps']} as const;\n"
        f"export const BACKTEST_RUN_EVENTS = {run_events} as const;\n"
    )


def generated_files(contract: dict[str, object]) -> dict[Path, str]:
    return {
        ROOT / "src" / "strategy_codebot" / "server" / "backtest_ohlcv_contract.py": render_python(contract),
        ROOT / "apps" / "web" / "src" / "lib" / "backtest-ohlcv-contract.ts": render_typescript(contract),
        ROOT / "workers" / "backtest-worker" / "src" / "backtest-ohlcv-contract.ts": render_typescript(contract),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    contract = load_contract()
    files = generated_files(contract)
    if args.write:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        return 0

    drifted = []
    for path, expected in files.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            actual = None
        if actual != expected:
            drifted.append(str(path.relative_to(ROOT)))
    if drifted:
        print("Backtest contract generated files are stale:")
        for path in drifted:
            print(f"- {path}")
        print("Run: scripts/sync-backtest-contracts.py --write")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
