// Generated by scripts/sync-chat-intent-registry.py. Do not edit by hand.

export const CHAT_RESPONSE_INTENTS = [
  "artifact_generation",
  "backtest_preview",
  "capability_help",
  "docs_research",
  "general_chat",
  "market_research",
  "market_snapshot",
  "pine_generation",
  "strategy_building"
] as const;

export type ChatResponseIntent = (typeof CHAT_RESPONSE_INTENTS)[number];

const CHAT_RESPONSE_INTENT_SET = new Set<string>(CHAT_RESPONSE_INTENTS);

export const CHAT_RESPONSE_INTENT_POLICIES = {
  "artifact_generation": {
    "allowedWorkflowIntents": [
      "strategy_to_paper_bot_simulation"
    ],
    "currentContextAllowed": false,
    "readonlyWebSearchAllowed": false,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": true
    }
  },
  "backtest_preview": {
    "allowedWorkflowIntents": [
      "strategy_to_paper_bot_simulation"
    ],
    "currentContextAllowed": false,
    "readonlyWebSearchAllowed": false,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": true
    }
  },
  "capability_help": {
    "allowedWorkflowIntents": [],
    "currentContextAllowed": true,
    "readonlyWebSearchAllowed": true,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": false
    }
  },
  "docs_research": {
    "allowedWorkflowIntents": [],
    "currentContextAllowed": true,
    "readonlyWebSearchAllowed": true,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": false
    }
  },
  "general_chat": {
    "allowedWorkflowIntents": [],
    "currentContextAllowed": false,
    "readonlyWebSearchAllowed": false,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": false
    }
  },
  "market_research": {
    "allowedWorkflowIntents": [],
    "currentContextAllowed": true,
    "readonlyWebSearchAllowed": true,
    "ui": {
      "marketToStrategySuggestion": true,
      "showStrategyProfile": false
    }
  },
  "market_snapshot": {
    "allowedWorkflowIntents": [],
    "currentContextAllowed": true,
    "readonlyWebSearchAllowed": true,
    "ui": {
      "marketToStrategySuggestion": true,
      "showStrategyProfile": false
    }
  },
  "pine_generation": {
    "allowedWorkflowIntents": [
      "strategy_to_paper_bot_simulation"
    ],
    "currentContextAllowed": false,
    "readonlyWebSearchAllowed": false,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": true
    }
  },
  "strategy_building": {
    "allowedWorkflowIntents": [
      "strategy_to_paper_bot_simulation"
    ],
    "currentContextAllowed": false,
    "readonlyWebSearchAllowed": false,
    "ui": {
      "marketToStrategySuggestion": false,
      "showStrategyProfile": true
    }
  }
} satisfies Record<
  ChatResponseIntent,
  {
    readonly currentContextAllowed: boolean;
    readonly readonlyWebSearchAllowed: boolean;
    readonly allowedWorkflowIntents: readonly string[];
    readonly ui: {
      readonly showStrategyProfile: boolean;
      readonly marketToStrategySuggestion: boolean;
    };
  }
>;

export function isChatResponseIntent(value: unknown): value is ChatResponseIntent {
  return typeof value === "string" && CHAT_RESPONSE_INTENT_SET.has(value);
}

export function shouldShowStrategyProfileForIntent(intent: ChatResponseIntent | null): boolean {
  return Boolean(intent && CHAT_RESPONSE_INTENT_POLICIES[intent]?.ui.showStrategyProfile);
}

export function shouldSuggestMarketToStrategyForIntent(intent: ChatResponseIntent | null): boolean {
  return Boolean(intent && CHAT_RESPONSE_INTENT_POLICIES[intent]?.ui.marketToStrategySuggestion);
}
