// Generated by scripts/sync-workflow-registry.py. Do not edit by hand.

export const WORKFLOW_SCHEMA_VERSION = 1 as const;
export const WORKFLOW_COMPONENT_KINDS = [
  "workflow_header",
  "badge_row",
  "step_checklist",
  "field_status_section",
  "artifact_refs_section",
  "review_status_section",
  "action_gate_section",
  "custom_adapter_section"
] as const;
export const WORKFLOW_DEFINITIONS = {
  "strategy_bot_simulation": {
    "id": "strategy_bot_simulation",
    "intent": "strategy_to_paper_bot_simulation",
    "title": "Strategy -> Paper Bot",
    "aria_label": "Strategy to Paper Bot workflow",
    "icon_key": "bot",
    "badges": [
      "Paper simulation only",
      "No broker execution",
      "Review-only evidence"
    ],
    "steps": [
      {
        "id": "collect_strategy_inputs",
        "label": "Collect strategy inputs"
      },
      {
        "id": "draft_strategy_spec",
        "label": "Draft strategy spec"
      },
      {
        "id": "generate_pine",
        "label": "Generate Pine strategy"
      },
      {
        "id": "static_validation",
        "label": "Static validation/repair"
      },
      {
        "id": "backtest_preview",
        "label": "Backtest preview"
      },
      {
        "id": "evidence_review",
        "label": "Evidence review"
      },
      {
        "id": "draft_bot_proposal",
        "label": "Draft Bot proposal"
      },
      {
        "id": "complete_setup_confirm_start",
        "label": "Complete setup + confirm paper start"
      }
    ],
    "status_labels": {
      "insufficient_evidence": {
        "key": "insufficient_evidence",
        "label": "Insufficient evidence",
        "tone": "neutral"
      },
      "reviewable_with_caveats": {
        "key": "reviewable_with_caveats",
        "label": "Reviewable with caveats",
        "tone": "success"
      },
      "needs_validation_or_robustness_check": {
        "key": "needs_validation_or_robustness_check",
        "label": "Needs validation or robustness check",
        "tone": "warning"
      }
    },
    "default_status_key": "insufficient_evidence",
    "allowed_section_kinds": [
      "field_status_section",
      "artifact_refs_section",
      "review_status_section",
      "action_gate_section",
      "custom_adapter_section"
    ],
    "allowed_fields": [
      "market",
      "symbol",
      "timeframe",
      "style",
      "entry_exit_idea",
      "risk_preference",
      "broker_connection_id",
      "account_id",
      "risk_policy_id",
      "strategy_id",
      "data_subscriptions"
    ],
    "required_input_fields": [
      "market",
      "symbol",
      "timeframe",
      "style",
      "risk_preference"
    ],
    "sections": [
      {
        "id": "strategy_inputs",
        "component_kind": "field_status_section",
        "title": "Strategy inputs",
        "fields": [
          "market",
          "symbol",
          "timeframe",
          "style",
          "entry_exit_idea",
          "risk_preference"
        ]
      },
      {
        "id": "paper_setup",
        "component_kind": "action_gate_section",
        "title": "Paper setup",
        "pending_label": "Waiting for fields",
        "ready_label": "Ready to confirm",
        "locked_message": "Start paper simulation is locked until setup is complete.",
        "action_id": "confirm_paper_start",
        "fields": [
          "broker_connection_id",
          "account_id",
          "risk_policy_id",
          "strategy_id",
          "data_subscriptions"
        ]
      }
    ],
    "actions": [
      {
        "id": "confirm_paper_start",
        "kind": "confirm_start_bot_proposal",
        "label": "Start paper simulation",
        "enabled": false,
        "disabled_reason": "Setup fields are incomplete."
      }
    ],
    "model_guidance": [
      "Use for Strategy to Paper Bot Simulation requests.",
      "Model may propose workflow intent and next step only; registry validates UI sections.",
      "Keep paper simulation boundaries visible.",
      "Do not represent broker execution or live trading evidence.",
      "Do not start runtime without proposal confirmation."
    ]
  }
} as const;
